import expense_categorizer_demo from "../assets/video/Java Expense Categorizer Project - 720p.mp4";
import expense_categorizer_img from "../assets/projects/ExpenseCategorizer.png";
import expense_categorizer_architecture from "../assets/projects/Expense_categorization_arch.png";
import greatHomes from "../assets/projects/great-homes.png";
import employeeManagementSystem from "../assets/projects/EMS.png";
import EMSArch from "../assets/projects/EMS_arch.png";
import greatHomes_Arch from "../assets/projects/GreatHomes-Arch.png";
import aiPortfolioAssistant from "../assets/projects/AI_stock_assistant.png";
// import aiPortfolioArch from "../assets/projects/ai-portfolio-arch.png";

const projects = [
  {
    id: 1,
    title: "RAG Chat API",
    description:
      "A robust FastAPI implementation of a Retrieval Augmented Generation system featuring real-time streaming, secure authentication, and session management.",
    imageUrl: null, // Placeholder: Add your image import here
    video: null,
    overview: (
      <div className="max-w-screen-md">
        <p className="mb-4">
          This project transforms a standalone RAG script into a production-ready{" "}
          <strong>FastAPI</strong> application. It maintains all the powerful
          capabilities of the original system—such as semantic chunking, ensemble
          retrieval, and LLM integration—while adding essential features for
          modern web deployment.
        </p>
        <p className="mb-4">
          The API supports <strong>Server-Sent Events (SSE)</strong> for real-time
          chat streaming, allowing users to see the query optimization process and
          answer generation as it happens. It also implements secure{" "}
          <strong>JWT authentication</strong> with HttpOnly cookies to manage user
          sessions and protect endpoints.
        </p>
        <p>
          With a focus on scalability and usability, this system handles multiple
          concurrent users, enforces rate limiting, and provides a comprehensive
          suite of endpoints for document management and conversation history.
        </p>
      </div>
    ),
    problemStatement: (
      <div className="max-w-screen-md">
        <h3 className="font-bold text-xl py-4">The Challenge:</h3>
        <p className="mb-4">
          Running complex RAG systems as standalone scripts limits their
          accessibility and usability. Single-user execution, lack of persistent
          state, and the inability to easily integrate with frontend applications
          are common bottlenecks when moving from a prototype to a production
          environment.
        </p>
        <p className="mb-4">Key limitations addressed include:</p>
        <ul className="list-disc mx-4 my-4">
          <li>
            <strong>Single-User Constraints:</strong> The original script could
            only process one interaction at a time.
          </li>
          <li>
            <strong>Integration Difficulties:</strong> No standard interface for
            web or mobile clients to communicate with the RAG engine.
          </li>
          <li>
            <strong>Security:</strong> Lack of authentication and session
            management mechanisms.
          </li>
          <li>
            <strong>Feedback Latency:</strong> Waiting for the full response
            generated by LLMs instead of receiving real-time tokens.
          </li>
        </ul>
        <p>
          The FastAPI implementation solves these by exposing RESTful endpoints,
          managing user sessions securely, and utilizing streaming protocols to
          enhance the user experience.
        </p>
      </div>
    ),
    techStack: [
      "FastAPI",
      "Python",
      "Pinecone Vector DB",
      "Google Gemini LLM",
      "JWT",
      "Server-Sent Events (SSE)",
      "Uvicorn",
    ],
    architecture: null,
    architectureFlowchart: {
      nodes: [
        { id: "frontend", label: "Frontend\n(React App)", type: "input" as const },
        { id: "auth", label: "JWT Auth\n(HttpOnly Cookie)", type: "auth" as const },
        { id: "fastapi", label: "FastAPI\n(app.py)", type: "process" as const },
        { id: "pinecone", label: "Pinecone\nVector DB", type: "database" as const },
        { id: "gemini", label: "Google\nGemini LLM", type: "llm" as const },
        { id: "session", label: "Session\nStore", type: "storage" as const },
      ],
      edges: [
        { from: "frontend", to: "auth", label: "Register/Login" },
        { from: "auth", to: "fastapi", label: "Validated Request" },
        { from: "fastapi", to: "pinecone", label: "Retrieval" },
        { from: "fastapi", to: "gemini", label: "Generate" },
        { from: "fastapi", to: "session", label: "Memory" },
      ],
      layout: "horizontal" as const,
    },
    features: [
      "RESTful API endpoints for chat, auth, and document management",
      "Real-time streaming responses using Server-Sent Events (SSE)",
      "Secure JWT Authentication with HttpOnly cookies",
      "Session-based rate limiting and history tracking",
      "Query optimization with rewriting and expansion",
      "Hybrid search (Vector + BM25) via Pinecone",
      "Semantic chunking for improved context retrieval",
    ],
    githubUrl: "https://github.com/shane-abh/RAG-Chat-API",
  },
  {
    id: 2,
    title: "AI Portfolio Assistant",
    description: "An AI-powered stock analysis and portfolio management tool that provides intelligent insights and recommendations for better investment decisions.",
    imageUrl: aiPortfolioAssistant,
    video: null,
    overview: (
      <div className="max-w-screen-md">
        <p>
          The <strong>AI Portfolio Assistant</strong> is a comprehensive stock analysis and portfolio management tool that leverages artificial intelligence to provide users with detailed insights into individual stocks and investment portfolios. The application helps investors make informed decisions by combining traditional financial metrics with AI-powered analysis.
        </p>
        <p>
          Built with <strong>Next.js</strong> and powered by <strong>LangChain</strong> and <strong>LLM</strong> technology, this platform offers a sophisticated yet user-friendly interface for analyzing stocks, managing portfolios, and receiving AI-generated investment recommendations.
        </p>
        <p>
          The system evaluates stocks based on multiple dimensions including valuation, growth potential, profitability, and risk assessment, providing users with comprehensive insights to make better investment decisions.
        </p>
      </div>
    ),
    problemStatement: (
      <div className="max-w-screen-md">
        <h3 className="font-bold text-xl py-4">The Challenge:</h3>
        <p className="mb-4">
          Investors often struggle to make informed decisions due to the overwhelming amount of financial data and the complexity of market analysis. Traditional tools either provide too much raw data without insights or offer oversimplified recommendations without proper analysis.
        </p>
        <p className="mb-4">
          The key challenges include:
        </p>
        <ul className="list-disc mx-4 my-4">
          <li>Difficulty in analyzing multiple data points across different timeframes</li>
          <li>Lack of comprehensive portfolio analysis and risk assessment</li>
          <li>Time-consuming process of gathering and interpreting financial data</li>
          <li>Need for personalized investment recommendations based on risk profile</li>
        </ul>
        <p className="mb-4">
          The AI Portfolio Assistant addresses these challenges by:
        </p>
        <ul className="list-disc mx-4 my-4">
          <li>Providing AI-powered analysis of stocks and portfolios</li>
          <li>Generating personalized investment recommendations</li>
          <li>Offering comprehensive risk assessment and growth potential analysis</li>
          <li>Automating the process of data gathering and interpretation</li>
        </ul>
      </div>
    ),
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "Recharts",
      "LangChain",
      "Groq LLM",
      "Alpha Vantage API",
      "Tiingo API"
    ],
    architecture: null,
    architectureFlowchart: {
      nodes: [
        { id: "nextjs", label: "Next.js\nApp", type: "input" as const },
        { id: "langchain", label: "LangChain\nOrchestrator", type: "api" as const },
        { id: "groq", label: "Groq\nLLM", type: "llm" as const },
        { id: "alphavantage", label: "Alpha Vantage\nStock Data", type: "service" as const },
        { id: "tiingo", label: "Tiingo\nMarket API", type: "service" as const },
      ],
      edges: [
        { from: "nextjs", to: "langchain" },
        { from: "langchain", to: "groq" },
        { from: "langchain", to: "alphavantage" },
        { from: "langchain", to: "tiingo" },
      ],
      layout: "three-tier" as const,
    },
    features: [
      "Stock Analysis Dashboard with comprehensive metrics and technical indicators",
      "AI-powered investment recommendations and scoring",
      "Portfolio analysis with diversification and risk assessment",
      "Interactive charts for visualizing stock data and trends",
      "Real-time data integration from multiple financial APIs",
      "AI-generated investment thesis and insights"
    ],
    githubUrl: "https://github.com/shane-abh/AI-portfolio-assistant"
  },
  {
    id: 3,
    title: "Expense Categorization API",
    description:
      "An AI-driven tool that automatically categorizes expenses with precision, saving time and eliminating manual errors.",

    imageUrl: expense_categorizer_img,
    video: expense_categorizer_demo,
    overview: (
      <p className="max-w-screen-md">
        Smart Finance is an AI-driven expense categorization tool designed to
        streamline the process of classifying expenses based on descriptions and
        amounts. Built with a <strong>Java Spring backend</strong> and a React
        frontend, Smart Finance harnesses the power of{" "}
        <strong>Llama 3.2b</strong>, a large language model, to deliver accurate
        and context-sensitive categorization without relying on manually defined
        rules or keywords. This tool is suited for individuals and businesses
        seeking a smarter, more efficient approach to managing expenses.",
      </p>
    ),
    problemStatement: (
      <div className="max-w-screen-md">
        <p className="mb-4 ">
          Categorizing expenses manually can be tedious and prone to error,
          particularly when descriptions are vague or inconsistent. Traditional
          methods often require hardcoded keywords or rigid rules, which can be
          limiting and inaccurate.
        </p>
        <p className="mb-4">
          Smart Finance addresses this issue by providing a
          machine-learning-based solution that understands context and
          categorizes expenses accordingly.
        </p>
        <p>Smart Finance solves the following issues:</p>
        <ul className="list-disc mx-4 my-4">
          <li>
            The need for manually defining keywords and rules, which can be
            inflexible and inaccurate.
          </li>
          <li>
            Difficulty in categorizing expenses with inconsistent or vague
            descriptions.
          </li>
          <li>
            The time-consuming nature of categorizing expenses individually,
            especially for bulk transactions.
          </li>
          <li>
            Potential errors in manual categorization, which can affect
            financial reporting accuracy.
          </li>
        </ul>
      </div>
    ),
    techStack: ["Java Spring boot", "llama 3.2b", "Typescript", "React"],
    architecture: expense_categorizer_architecture,
    architectureFlowchart: {
      nodes: [
        { id: "react", label: "React\nFrontend", type: "input" as const },
        { id: "spring", label: "Spring Boot\nAPI", type: "process" as const },
        { id: "ollama", label: "Llama 3.2b\n(Ollama)", type: "llm" as const },
      ],
      edges: [
        { from: "react", to: "spring" },
        { from: "spring", to: "ollama" },
      ],
      layout: "simple" as const,
    },
    features: [
      "Users can enter individual expense descriptions and amounts for immediate categorization.",
      "Supports CSV file uploads for batch categorization, enabling users to process multiple expenses at once.",
      "Utilizes the Llama 3.2b model to interpret the context behind descriptions, eliminating the need for static keywords",
      "Adapts to various expense types, enhancing categorization accuracy with natural language processing (NLP)",
    ],
    githubUrl: "https://github.com/shane-abh/expense-categorizer",
  },
  {
    id: 4,
    title: "Great Homes",
    description:
      "An all-in-one real estate platform to find properties, calculate mortgages, and manage listings effortlessly. ",

    imageUrl: greatHomes,
    video: null,

    overview: (
      <div>
        <p>
          We've designed <strong>Great Homes</strong> to tackle these challenges
          head-on. It's a platform that brings everything you need to find,
          finance, and finalize your home purchase, all in one place.
        </p>

        <p>
          With <strong>Great Homes</strong>, you can search for properties,
          calculate your mortgage, contact landlords, and manage your Wishlist
          all within a single, user-friendly platform. No more jumping between
          different websites or apps. Everything you need is right here, making
          your home-buying journey smoother and more enjoyable.
        </p>

        <p>
          Our goal is to make this process as stress-free as possible. By
          combining property listings with powerful financial tools and a
          streamlined contact process, <strong>Great Homes</strong> gives you
          confidence in every decision you make.
        </p>

        <p>
          Whether you're a first-time buyer or a seasoned investor,{" "}
          <strong>Great Homes</strong> is designed to meet your needs. We've
          integrated cutting-edge technology with a user-friendly design to save
          you time and empower you to make informed, confident choices in the
          real estate market.
        </p>
      </div>
    ),
    problemStatement: (
      <div>
        <h3>Let's Talk About the Current Home-Buying Experience</h3>

        <h4 className=" font-semibold text-lg my-2">A Fragmented Journey:</h4>
        <p>
          As a homebuyer, you've probably felt the frustration of navigating
          through multiple websites and tools just to find the right property.
          You search for homes on one platform, then jump to another to
          calculate mortgage payments, and perhaps even a third service to keep
          track of your favorites. This disconnected process not only takes up
          your time but also adds unnecessary stress to what should be an
          exciting journey.
        </p>

        <h4 className=" font-semibold text-lg my-2">
          Lack of Seamless Integration:
        </h4>
        <p>
          Now, imagine trying to figure out how much house you can afford, but
          having to leave the property listing site to do so. And when you
          finally find a property you like, you need yet another tool to contact
          the landlord or manage your wishlist. This lack of integration is not
          only frustrating but also increases the risk of errors and missed
          opportunities.
        </p>

        <h4 className=" font-semibold text-lg my-2">
          The Challenges You Face:
        </h4>
        <p>
          The real estate market is full of options, and it's easy to feel
          overwhelmed without the right tools to filter and analyze your
          choices. You need a solution that not only helps you find the perfect
          property but also guides you through the financial aspects of buying a
          home.
        </p>
      </div>
    ),
    techStack: [
      "React.js",
      "MongoDB",
      "Firebase",
      "Redux",
      "Express",
      "Node.js",
    ],
    architecture: greatHomes_Arch,
    architectureFlowchart: {
      nodes: [
        { id: "react", label: "React\n+ Redux", type: "input" as const },
        { id: "firebase", label: "Firebase\nAuth", type: "auth" as const },
        { id: "express", label: "Express\nAPI", type: "process" as const },
        { id: "mongodb", label: "MongoDB\nDatabase", type: "database" as const },
      ],
      edges: [
        { from: "react", to: "firebase" },
        { from: "firebase", to: "express" },
        { from: "express", to: "mongodb" },
      ],
      layout: "three-tier" as const,
    },
    features: [
      "Search and filter properties",
      "Mortgage calculator for properties on sale",
      "Contact landlord via email",
      "Social sign in",
      "Create, update, and delete your listings",
    ],
    githubUrl: "https://github.com/shane-abh/Great-Homes",
  },
  {
    id: 5,
    title: "Employee Management System",
    description : "A centralized solution for managing employee data, tracking performance, and streamlining HR processes with ease.",
    imageUrl: employeeManagementSystem,
    video: null,
    overview: (
      <div className="">
        <p>
          We've built the <strong>Employee Management System (EMS)</strong> to
          tackle the common challenges of managing employee data head-on. It's a
          comprehensive platform that centralizes everything you need to track,
          manage, and update employee information—all in one place.
        </p>

        <p>
          With the EMS, you can easily add and manage employee records, update
          their details, track performance, and securely store all relevant
          information in real-time. No more juggling between multiple tools or
          dealing with scattered data. Everything you need is right here, in a
          single, user-friendly interface that makes managing your workforce
          simpler and more efficient.
        </p>

        <p>
          Our goal is to make employee management as seamless as possible. By
          integrating a powerful backend with a user-friendly frontend, the EMS
          gives you the confidence to make informed decisions about your
          workforce. Whether you're handling hiring, performance tracking, or
          data updates, this system empowers you to stay organized and in
          control.
        </p>

        <p>
          Whether you're a small business owner or managing a large team, the{" "}
          <strong>Employee Management System</strong> is designed to meet your
          needs. We've combined cutting-edge technology with an intuitive design
          to help you save time, eliminate errors, and maintain up-to-date
          employee information effortlessly.
        </p>
      </div>
    ),
    problemStatement: (
      <div>
        <h3 className="font-bold text-xl py-4">Problem:</h3>
        <p>
          Managing employee data manually or through spreadsheets can lead to
          inefficiencies, errors, and a lack of centralization. This makes it
          difficult for organizations to track employee information, such as
          contact details, roles, performance, and other relevant data, in a
          streamlined and secure manner. Without a robust system, there is also
          a lack of real-time updates, easy access to data, and a risk of data
          inconsistency across different departments.
        </p>

        <h3 className="font-bold text-xl py-4">Solution:</h3>
        <p>
          The <strong>Employee Management System</strong> solves this problem by
          providing a centralized platform where:
        </p>
        <ul className="list-disc m-4">
          <li>
            Employee data can be stored, accessed, and updated in real-time.
          </li>
          <li>
            The system uses <strong>MongoDB</strong> to store employee
            information, ensuring scalability and efficient data management.
          </li>
          <li>
            The backend, built with <strong>Node.js</strong> and{" "}
            <strong>Express</strong>, handles data management and business
            logic, allowing for secure access and manipulation of employee data.
          </li>
          <li>
            The frontend, built using <strong>React.js</strong>, provides a
            user-friendly interface for interacting with employee records.
          </li>
          <li>
            <strong>GraphQL</strong> is used for communication between the front
            and back ends, allowing efficient querying and real-time updates.
          </li>
        </ul>

        <p>
          This solution enhances data accuracy, provides easy access to employee
          information, and streamlines management tasks within an organization.
          It addresses common challenges such as data redundancy, slow updates,
          and difficulty in retrieving employee details.
        </p>
      </div>
    ),
    techStack: ["React", "MongoDB", "Bootstrap", "Node.js", "GraphQL"],
    architecture: EMSArch,
    architectureFlowchart: {
      nodes: [
        { id: "react", label: "React\nFrontend", type: "input" as const },
        { id: "graphql", label: "GraphQL\nAPI Layer", type: "api" as const },
        { id: "nodejs", label: "Node.js\nServer", type: "process" as const },
        { id: "mongodb", label: "MongoDB\nDatabase", type: "database" as const },
      ],
      edges: [
        { from: "react", to: "graphql" },
        { from: "graphql", to: "nodejs" },
        { from: "nodejs", to: "mongodb" },
      ],
      layout: "three-tier" as const,
    },
    features: [
      "Search and filter employees",
      "Create, update, and delete employees",
      "Check employees close to the retirement dates",
    ],
    githubUrl: "https://github.com/shane-abh/Employee-Management-System",
  },
  {
    id: 6,
    title: "Budget 2025 Navigator",
    description:
      "An interactive RAG-powered chat interface for exploring Canada's Budget 2025, featuring real-time query optimization, source citations, and a blueprint-themed UI.",
    imageUrl: null,
    video: null,
    overview: (
      <div className="max-w-screen-md">
        <p className="mb-4">
          The <strong>Budget 2025 Navigator</strong> is a sophisticated React-based chat interface that connects to a FastAPI RAG backend, enabling users to explore Canada's Budget 2025 documents through natural language queries. The application features a distinctive "blueprint" design theme inspired by construction and engineering aesthetics.
        </p>
        <p className="mb-4">
          Built with <strong>React</strong> and <strong>TypeScript</strong>, the frontend implements real-time streaming via Server-Sent Events (SSE), allowing users to see query optimization and answer generation as it happens. The UI showcases query rewriting, term expansion, and source citations in an intuitive, accordion-based interface.
        </p>
        <p>
          The application includes secure JWT authentication, session management, and a questions-per-session limit system. Users can explore tax changes, infrastructure investments, housing policies, and other budget-related topics with AI-powered responses backed by official government documents.
        </p>
      </div>
    ),
    problemStatement: (
      <div className="max-w-screen-md">
        <h3 className="font-bold text-xl py-4">The Challenge:</h3>
        <p className="mb-4">
          Government budget documents are dense, technical, and difficult for citizens to navigate. Finding specific information about tax changes, program details, or policy implications requires reading through hundreds of pages of documentation. This creates a barrier to understanding how the budget affects individuals and businesses.
        </p>
        <p className="mb-4">Key challenges addressed include:</p>
        <ul className="list-disc mx-4 my-4">
          <li>
            <strong>Information Accessibility:</strong> Budget documents are lengthy and technical, making it difficult for citizens to find relevant information quickly.
          </li>
          <li>
            <strong>Query Understanding:</strong> Users may not know the exact terminology or phrasing used in official documents.
          </li>
          <li>
            <strong>Source Transparency:</strong> Users need to know where information comes from to verify accuracy.
          </li>
          <li>
            <strong>Real-time Feedback:</strong> Waiting for complete responses can feel slow and unresponsive.
          </li>
        </ul>
        <p>
          The Budget 2025 Navigator solves these challenges by providing an intuitive chat interface that understands natural language queries, optimizes them for better retrieval, and provides real-time streaming responses with source citations. The blueprint-themed UI creates a professional, government-appropriate aesthetic while remaining modern and accessible.
        </p>
      </div>
    ),
    techStack: [
      "React",
      "TypeScript",
      "Server-Sent Events (SSE)",
      "React Markdown",
      "JWT Authentication",
      "FastAPI Backend",
      "Pinecone Vector DB",
      "Google Gemini LLM",
    ],
    architecture: null,
    architectureFlowchart: {
      nodes: [
        { id: "react", label: "React\nFrontend", type: "input" as const },
        { id: "sse", label: "SSE\nStreaming", type: "api" as const },
        { id: "fastapi", label: "FastAPI\nBackend", type: "process" as const },
        { id: "pinecone", label: "Pinecone\nVector DB", type: "database" as const },
        { id: "gemini", label: "Google\nGemini LLM", type: "llm" as const },
        { id: "jwt", label: "JWT\nAuth", type: "auth" as const },
      ],
      edges: [
        { from: "react", to: "sse" },
        { from: "sse", to: "fastapi" },
        { from: "fastapi", to: "pinecone" },
        { from: "fastapi", to: "gemini" },
        { from: "react", to: "jwt" },
        { from: "jwt", to: "fastapi" },
      ],
      layout: "three-tier" as const,
    },
    features: [
      "Real-time streaming chat interface with Server-Sent Events",
      "Query optimization with automatic rewriting and term expansion",
      "Source citations with document references",
      "Blueprint-themed UI with Canadian government aesthetic",
      "JWT authentication with session management",
      "Questions-per-session limit tracking",
      "Markdown rendering for formatted responses",
      "Responsive design for mobile and desktop",
    ],
    githubUrl: "https://github.com/shane-abh/RAG-Chat-API",
  }
];

export default projects;
